version: '3'

tasks:
  install-deps:
    desc: "Install Node.js dependencies for development"
    dir: virtual-dm
    cmd: npm install

  run-dev:
    desc: "Run the Next.js development server"
    deps: [install-deps]
    dir: virtual-dm
    cmd: npm run dev
    
  build:
    desc: "Build the Docker image for the Virtual DM application"
    cmd: docker build -t virtual-dm .
    
  docker-run:
    desc: "Build and run the Docker container"
    deps: [build]
    cmd: docker run -p 3000:3000 virtual-dm
    
  docker-run-ci:
    desc: "Build and run the Docker container in the background"
    deps: [build]
    cmd: docker run -d --name virtual-dm-app -p 3000:3000 --restart unless-stopped virtual-dm
